P = {
    lspconfig = {enabled = true},
    lspsaga = {enabled = true},
    lspinstall = {enabled = true},
    popup = {enabled = true},
    plenary = {enabled = true},
    telescope = {enabled = true},
    telescopeFzy = {enabled = true},
    dap = {enabled = true},
    compe = {enabled = true},
    vsnip = {enabled = true},
    friendlySnippets = {enabled = true},
    treesitter = {enabled = true},
    tsAutotag = {enabled = true},
    nvimTree = {enabled = true},
    rnvimr = {enabled = true},
    gitsigns = {enabled = true},
    whichkey = {enabled = true},
    dashboard = {enabled = true},
    autopairs = {enabled = true},
    comment = {enabled = true},
    bqf = {enabled = true},
    nvcodeColorschemes = {enabled = true},
    webDevicons = {enabled = true},
    galaxyline = {enabled = true},
    barbar = {enabled = true}
}
